<Image_test@FloatLayout>

    FloatLayout:
        canvas.before:
            Color:
                hsv: 1, 0, 1
            Rectangle:
                # self here refers to the widget i.e BoxLayout
                pos: self.pos
                size: self.size
            BorderImage:
                source: "bakkun_without_back_ground.png"
                size: 400, 400
                pos: 200, 50
            BorderImage:
                source: "fukidashi.png"
                size: 250, 150
                pos: 500, 400

    Label:  # add comment   
        text: "ようこそ！"
        color: 1,0,1,1
        font_size: 25
        pos: 230, 190

        


    FloatLayout:
        Button:
            on_press: app.root.go_to_ask_take_photo(), app.root.send_selected_key("y")
            # size: 100, 100
            font_size: 30
            pos:100, 400
            size_hint: .2, .2 

        

